
[theme]
primaryColor = "#4A5F44"       # Vert pin doux
backgroundColor = "#FDF6EC"    # Beige clair
secondaryBackgroundColor = "#EAEAEA"  # Gris perle
textColor = "#000000"          # Noir
font = "sans serif"


[server]
headless = true

[client]
showSidebarNavigation = true

[browser]
title = "Visualisation Salomon"
favicon = "https://upload.wikimedia.org/wikipedia/commons/5/5f/Salomon-logo.png"
